config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :customers, only: %i(new create) do
    resources :tickets, module: 'customers', except: :destroy
  end

  resources :tickets, except: %i(new create destroy) do
    get :search,  on: :collection

    resources :replies, only: %i(index new create)
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_uniqueness_of :email

  has_many :tickets, foreign_key: 'creator_id'
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :ticket

  belongs_to :new_owner, class_name: 'User'
  belongs_to :new_status, class_name: 'Status'

  validates_presence_of :ticket

  after_create :update_ticket

  private

  def update_ticket
    ticket.update_attributes(owner_id: new_owner_id, status_id: new_status_id)
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  DEFAULT_STATUSES = ['Waiting for Staff Response', 'Waiting for Customer', 'On Hold', 'Cancelled', 'Completed']

  WAITING_FOR_STAFF = 'Waiting for Staff Response'
  WAITING_FOR_CUSTOMER = 'Waiting for Customer'
  ON_HOLD = 'On Hold'
  CANCELLED = 'Cancelled'
  COMPLETED = 'Completed'

  validates_uniqueness_of :name

  scope :waiting_for_staff_response, -> { find_by(name: WAITING_FOR_STAFF) }
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates_uniqueness_of :reference, allow_nil: true

  belongs_to :creator, class_name: 'Customer'
  belongs_to :owner, class_name: 'User'
  belongs_to :status

  has_many :replies

  before_create :generate_reference, :normalize_status

  scope :on_hold, -> { joins(:status).where(statuses: {name: Status::ON_HOLD}) }
  scope :closed, -> { joins(:status).where(statuses: {name: [Status::CANCELLED, Status::COMPLETED]}) }

  searchable do
    text :description, :title, :reference
  end

  def to_param
    reference
  end

  def self.open
    joins(:status)
        .where(statuses: {name: [Status::WAITING_FOR_STAFF, Status::WAITING_FOR_CUSTOMER]}, owner_id: nil)
  end

  private

  def generate_reference
    self.reference = TicketReferenceGenerator.new.reference
  end

  def normalize_status
    self.status ||= default_status
  end

  def default_status
    Status.waiting_for_staff_response
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers/tickets_controller.rb
class Customers::TicketsController < ApplicationController
  before_action :find_customer
  before_action :find_ticket, except: %w(new create)

  def index
    if @customer.tickets.where(reference: params[:reference])
      @tickets = @customer.tickets.paginate(page: params[:page])
    else
      flash[:alert] = t('customers.tickets.index.access_error')
      redirect_to new_customer_ticket_path(@customer)
    end
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params.merge(creator_id: @customer.id))

    if @ticket.save
      flash[:success] = t('customers.tickets.create.success')
      CustomerMailer.new_ticket(@ticket).deliver_later

      redirect_to new_customer_ticket_path(@customer)
    else
      flash[:alert] = @ticket.errors.full_messages.join(', ')

      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @ticket.assign_attributes(ticket_params)

    if @ticket.save
      flash[:success] = t('customers.tickets.update.success')
      CustomerMailer.updated_ticket(@ticket).deliver_later

      redirect_to customer_ticket_path(@customer, @ticket)
    else
      flash[:alert] = @ticket.errors.full_messages.join(', ')

      render :edit
    end
  end

  private

  def find_customer
    @customer = Customer.find(params[:customer_id])
  end

  def find_ticket
    @ticket = @customer.tickets.find_by(reference: params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:title, :description)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.find_or_initialize_by(customer_params)

    if @customer.save
      flash[:success] = t('customers.create.welcome', name: @customer.name)

      redirect_to new_customer_ticket_path(@customer)
    else
      flash[:danger] = @customer.errors.full_messages.join(', ')

      render :new
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_ticket

  def index
    @replies = @ticket.replies.paginate(page: params[:page])
  end

  def new
    @reply = @ticket.replies.new
  end

  def create
    @reply = @ticket.replies.new(reply_params)

    if @reply.save
      flash[:success] = t('replies.create.success')

      redirect_to ticket_replies_path(@ticket.id)
    else
      flash[:alert] = @reply.errors.full_messages.join(', ')

      render :new
    end
  end

  private

  def find_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def reply_params
    params.require(:reply).permit(:body, :new_status_id, :new_owner_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!

  before_action :find_ticket, except: %i(index search)

  def index
    @tickets = case params[:tickets_type]
      when 'on_hold'
        Ticket.on_hold
      when 'open'
        Ticket.open
      when 'closed'
        Ticket.closed
      else
        Ticket.all
      end

    @tickets = @tickets.paginate(page: params[:page])
  end

  def edit

  end

  def update
    @ticket.assign_attributes ticket_params

    if @ticket.save
      flash[:success] = t('tickets.update.success')

      redirect_to ticket_path(@ticket.id)
    else
      flash[:alert] = @ticket.errors.full_messages.join(', ')

      render :edit
    end
  end

  def show

  end

  def search
    @tickets = Ticket.search do
      fulltext params[:query]
    end.results
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :description, :owner_id, :status_id)
  end

  def find_ticket
    @ticket = Ticket.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    base_title = t('title')

    if title.empty?
      base_title
    else
      "#{base_title} | #{title}"
    end
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
  def new_owner(reply)
    reply.new_owner.try(:email) || t('replies.owner_unassigned')
  end
end

app/views/customers/new.html.haml
= form_for @customer  do |f|
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Login', class: 'btn btn-default'

app/views/customers/tickets/_form.html.haml
= form_for [@customer, @ticket] do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'

  = f.submit t(".#{action_name}_button"), class: 'btn btn-primary'

app/views/customers/tickets/_ticket.html.haml
%tr
  %td= link_to ticket.title, customer_ticket_path(ticket.creator, ticket)
  %td= ticket.description
  %td= ticket.status.try(:name)
  %td= link_to t('actions.edit'), edit_customer_ticket_path(ticket.creator, ticket)

app/views/customers/tickets/edit.html.haml
%h3= t('.title')

= render 'form'

app/views/customers/tickets/index.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th= t('.title')
      %th= t('.description')
      %th= t('.status')
      %th= t('actions.title')
  %tbody
    = render @tickets

= will_paginate @tickets, renderer: BootstrapPagination::Rails

app/views/customers/tickets/new.html.haml
%h3= t('.title')

= render 'form'

app/views/customers/tickets/show.html.haml
%p= link_to t('.index'), customer_tickets_path(@customer, reference: @ticket.reference)
= link_to t('actions.edit'), edit_customer_ticket_path(@customer, @ticket), class: 'btn btn-primary'

%h2= t('.title')
%p= @ticket.title

%h2= t('.description')
%p= @ticket.description

app/views/home/index.html.haml
.row
  %h2= t('title')

- if user_signed_in?
  .row
    %blockquote= t('.signed_in', email: current_user.email)
    %p= link_to t('.tickets'), tickets_path(tickets_type: :all)

    = link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'btn btn-danger'
- else
  .row
    = link_to t('.sign_in'), new_user_session_path, class: 'btn btn-success'
    = link_to t('.sign_up'), new_user_registration_path, class: 'btn btn-primary'
    = link_to t('.for_customers'), new_customer_path, class: 'btn btn-info'

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-static-top.navbar-inverse
    .container-fluid
      .navbar-header
        = link_to t('title'), root_path, class: 'navbar-brand'
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li= link_to 'Home', root_path, class: 'active'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', data: { turbolinks_track: true }
    = javascript_include_tag 'application', data: { turbolinks_track: true }
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      .msg
        - flash.each do |key, value|
          %div{class: "alert alert-#{key}", role: 'alert'}= value
      = yield

app/views/replies/_form.html.haml
= form_for [@ticket, @reply], url: ticket_replies_path(@ticket.id, @reply) do |f|
  .form-group
    = f.label :body
    = f.text_field :body, class: 'form-control'

  .form-group
    = label_tag 'reply_new_owner_id'
    = select_tag 'reply[new_owner_id]', options_from_collection_for_select(User.all, 'id', 'email', @ticket.owner_id),
      include_blank: true, class: 'form-control'

  .form-group
    = label_tag 'reply_new_status_id'
    = select_tag 'reply[new_status_id]', options_from_collection_for_select(Status.all, 'id', 'name', @ticket.status_id),
      include_blank: true, class: 'form-control'

  = f.submit t(".#{action_name}_button"), class: 'btn btn-primary'

app/views/replies/_reply.html.haml
%tr
  %td= reply.body
  %td= reply.new_status.name
  %td= new_owner reply
  %td= reply.created_at

app/views/replies/index.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th= t('.body')
      %th= t('.new_status')
      %th= t('.new_owner')
      %th= t('.time')
  %tbody
    = render @replies

= will_paginate @replies, renderer: BootstrapPagination::Rails

app/views/replies/new.html.haml
%h3= t('.title')

= render 'form'

app/views/tickets/_form.html.haml
= form_for @ticket, url: ticket_path(@ticket.id) do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'

  .form-group
    = label_tag 'ticket_owner_id'
    = select_tag 'ticket[owner_id]', options_from_collection_for_select(User.all, 'id', 'email', @ticket.owner_id),
      include_blank: true, class: 'form-control'

  .form-group
    = label_tag 'status_id'
    = select_tag 'ticket[status_id]', options_from_collection_for_select(Status.all, 'id', 'name', @ticket.status_id),
      include_blank: true, class: 'form-control'

  = f.submit t(".#{action_name}_button"), class: 'btn btn-primary'

app/views/tickets/_ticket.html.haml
%tr
  %td= link_to ticket.title, ticket_path(ticket.id)
  %td= ticket.description
  %td= ticket.status.try(:name)
  %td= link_to t('actions.edit'), edit_ticket_path(ticket.id)

app/views/tickets/_ticket_nav.html.haml
%li{class: params[:tickets_type] == nav_type && 'active'}= link_to t(".#{nav_type}"), tickets_path(tickets_type: nav_type)

app/views/tickets/_tickets.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th= t('.title')
      %th= t('.description')
      %th= t('.status')
      %th= t('actions.title')
  %tbody
    = render @tickets

= will_paginate @tickets, renderer: BootstrapPagination::Rails

app/views/tickets/edit.html.haml
%h3= t('.title')

= render 'form'

app/views/tickets/index.html.haml
%ul.nav.nav-tabs
  - %w(all on_hold open closed).each do |nav_type|
    = render 'ticket_nav', nav_type: nav_type

= render 'tickets'

app/views/tickets/search.html.haml
%h3= t('.search_results')

= render 'tickets'

app/views/tickets/show.html.haml
%p= link_to t('.index'), tickets_path(tickets_type: :all)

= link_to t('actions.edit'), edit_ticket_path(@ticket.id), class: 'btn btn-primary'

%h2= t('.title')
%p= @ticket.title

%h2= t('.description')
%p= @ticket.description

%h2= t('.status')
%p= @ticket.status.name

- if @ticket.owner
  %h2= t('.owner')
  %p= @ticket.owner.email